config/routes.rb
Rails.application.routes.draw do



  ActiveAdmin.routes(self)
  root 'layouts#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  
  get '/blog' => "layouts#show"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  get '/shop', to: 'products#index'
  resources :orders
  resources :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :line_items, dependent: :destroy

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end

  def total_price_include_vat
    sum = line_items.to_a.sum {|item| item.total_price} + ((line_items.to_a.sum {|item| item.total_price} * 10) / 100)
    return sum + ((sum * 10)/ 100)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :correct_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = @current_cart
  end

  # GET /carts/new
  def new
    @cart = Cart.create
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.create(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    flash[:success] = "Cart deleted"
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id)
    end

    def correct_cart
      @cart = Cart.find(params[:id])
      redirect_to(root_path) unless @cart == current_cart
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "Invalid cart"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_carts.html.erb
<% @cart.line_items.each do |line_item| %>
    <%= render partial: "line_item", locals: {line_item: line_item} %>
<% end %>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :cart_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/_line_item.html.erb
<%= image_tag(line_item.product.image.url(:medium), id: "img_pro") %>
<div id="p_npro">
    <p><%= line_item.product.name %></p>
    <p style="font-size:85%;color:tomato;"><i>Only <%= line_item.product.total %> left in stock</i></p>
</div>
<p id="p_dolar"><%= number_to_currency(line_item.product.price) %></p>
<div>
    <%= link_to '<i class="fa fa-minus-square" aria-hidden="true"></i>'.html_safe,line_item_reduce_path(:id => line_item), method: :post, remote: true ,id: "reduct-item" %> 
     <%= line_item.quantity %>
    <%= link_to '<i class="fa fa-plus-square" aria-hidden="true"></i>'.html_safe, line_item_add_path(:id => line_item), method: :post, remote: true, id: "add-item" %>
</div>
<%= link_to "Delete", line_item, method: :delete %>

app/views/carts/_line_item1.html.erb
<p id="cost1" style="margin-top: -50px;"><%= line_item.product.name %> &times; <%= line_item.quantity %></p>

app/views/carts/_show_cart.html.erb
<p id="infor1">PRODUCT INFORMATION</p>
<p id="infor2">Provisional :</p>
<% @cart.line_items.each do |line_item| %>
    <%= render partial: "line_item1", locals: {line_item: line_item} %>
<% end %>
<p id="infor3">Total :</p>
<p id="cost2" style="height: 100%; margin-bottom: -45px;"><%= @cart.total_price %></p>
<% if @cart.line_items.count > 0 %>
<%= button_to "CARRY OUT PAYMENT", new_order_path, :style => "border:none;padding:20px;background:tomato;color:white;", method: :get %><br>
<%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"}, :style => 'margin-left: -120px' %>
<% else %>
<%= button_to "Let's Buy Products", shop_path, method: :get, :style => "border:none;padding:20px;background:tomato;color:white;" %>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="content4">
    <div id="header_cart">        
          <p>MY SHOPPING CART <i class="fa fa-shopping-cart" aria-hidden="true"></i></p>     
      </div>
     
     <div class="cart2">
        <div id="p"><a href="shop.php"><p><i class="fa fa-chevron-left" aria-hidden="true"></i> Continue</p></a></div>
        <div class="cart_2">
             <div class="my_cart">
                <p id="p_mycart"><strong>My Shopping Cart</strong></p>
                <!--<p id="p_pro">My products</p>
                <p id="p_cost">Quantity</p>
                <p id="p_amount">Total</p>-->
                <div id="carts">
                    <%= render 'carts' %>
                </div>
               
            </div>
                <div class="info_cart">
                    <%= render 'show_cart' %>
                </div>
        </div>
       
     </div>
  
   </div>