config/routes.rb
Rails.application.routes.draw do



  ActiveAdmin.routes(self)
  root 'layouts#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  
  get '/blog' => "layouts#show"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  get '/shop', to: 'products#index'
  resources :orders
  resources :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

has_many :line_items, dependent: :destroy
before_destroy :ensure_not_referenced_by_any_line_item


scope :out_of_stock, -> { where('total <= 0')}
scope :starts_with, -> (name) { where("name like ?", "#{name}%")}
scope :catalog, -> (catalog) {where catalog: catalog}
    enum catalog: {
        "Leafy and salad vegetables" => 1,
        "Fruits" => 2,
        "Flowers and flower buds" => 3,
        "Podded vegetables" => 4,
        "Bulb and stem vegetables" => 5,
        "Root and tuberous vegetables" => 6,
        "Sea vagetables" => 7
    }
VALID_INTEGER = /\A[0-9]+\z/i
has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
validates :name, presence: true, length: {minimum: 4}
validates :price, presence: true, numericality: {only_integer: false, greater_than_or_equal_to: 0}
validates :discount, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
validates :description, presence: true, length: {maximum: 250}
validates :total, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
validates :catalog, presence: true, inclusion: {in: catalogs.keys}
validates :source, presence: true

def count_view
    sum = view + 1
    self.update_attribute(:view, sum)
    return sum
end

def price_discout
    price - ((price * discount)/100)
end
private
    def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, 'Line items present')
            throw :abort
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource :except => [:index, :show]
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path
  end
  
  def index
    @product = Product.order('view desc').limit(5)
    @products = Product.where(nil).paginate(:page => params[:page], :per_page => 9)
    @products = @products.catalog(params[:catalog]).paginate(:page => params[:page], :per_page => 9) if params[:catalog].present?
    @products = @products.starts_with(params[:starts_with]).paginate(:page => params[:page], :per_page => 9) if params[:starts_with].present?
  end

  def show  
    @product = Product.find(params[:id])
    @product.count_view
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash.now[:success] = "Create product complete"
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find_by(params[:id])
  end

  def update
    @product = Product.find_by(params[:id])
    if @product.update_attributes(product_params)
      flash[:success] = "Create product success"
      redirect_to products_path
    else
      flash[:danger] = "Error"
      render 'edit'
    end
  end

  def destroy
    if Product.find(params[:id]).destroy
    flash[:success] = "Product deleted"
    redirect_to root_path
    else
    flash[:danger] = "We still have orders of this product"
    redirect_to root_path
    end
    
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :discount, :description, :view, :total, :catalog, :image ,:source)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="vegets">
        <%= link_to product_path(product) do %>
        <% if product.discount > 0 %>
        <div class="discout_shop"><p style="color:white;padding:15px;background:tomato;margin-left:150px;margin-top:-7px;position: absolute;">-<%= product.discount %>%</p></div>
        <% end %>
            <%= image_tag(product.image.url(:medium)) %>
            <p style="line-height: 1.2;"><%= product.name %></p>
            <p style="color:red; font-style: italic; font-size:16px;"><%= number_to_currency(product.price) %></p>
        <% end %>
</div>

app/views/products/_products.html.erb
<% @products.each do |product| %>
    <%= render partial: "product", locals: {product: product} %>
<% end %>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>

<% if @product.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@product.errors.count, "error") %>.
        </div>
        <ul>
            <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :price %>
    <%= f.number_field :price %>

    <%= f.label :discount %>
    <%= f.number_field :discount %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, cols: 50 %>

    <%= f.label :total %>
    <%= f.number_field :total %>

    <%= f.label :image %>
    <%= f.file_field :image %>

    <%= f.label :catalog %>
    <%= f.select :catalog, Product.catalogs.keys, prompt: "Select catalog for product" %>
    

    <%= f.label :source %>
    <%= f.country_select :source %>


    <%= f.submit "Update product" %>
<% end %>

app/views/products/index.html.erb
<div class="content2">
        <div id="header-name">
            <p>LET's  SHOPPING  <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></p>
        </div>
        <div class="tonghop">
            <div class="tonghop1">
               <div id="categories">
                       <div class="cate">
                           <p>CATEGORIES</p>
                       </div>
                       <ul id="choose">
                            <li><%= link_to "All Items", products_path, remote: true %></li>
                            <li><%= link_to "Leafy and salad vegetables", products_path(:catalog => 'Leafy and salad vegetables'), remote: true %></li>
                            <li><%= link_to "Fruits", products_path(:catalog => 'Fruits'), remote: true %></li>
                            <li><%= link_to "Flowers and flower buds", products_path(:catalog => 'Flowers and flower buds'), remote: true %></li>
                            <li><%= link_to "Podded vegetables", products_path(:catalog => 'Podded vegetables'), remote: true %></li>
                            <li><%= link_to "Bulb and stem vegetables", products_path(:catalog => 'Bulb and stem vegetables'), remote: true %></li>
                            <li><%= link_to "Root and tuberous vegetables", products_path(:catalog => 'Root and tuberous vegetables'), remote: true %></li>
                            <li><%= link_to "Sea vagetables", products_path(:catalog => 'Sea vagetables'), remote: true %></li>
                       </ul>
                </div>
               <div id="bestseller">
                   <div class="cate">
                       <p>BESTSELLER</p>
                   </div>
                   <ul id="choose">
                       <% @product.each do |product| %>
                       <li><%= link_to product.name, product_path(product) %></li>
                       <% end %>
                   </ul>
               </div>
           </div>
           <div class="tonghop2">
               <div id="featured">
                   <div id="featured-product">
                         <p>FEATURED PRODUCTS </p>
                        <div class="search ">
                                <%= form_tag products_path, remote: true, method: :get do |f| %>    
                                    <%= label_tag 'starts_with', '<i class="fa fa-search" aria-hidden="true"></i>'.html_safe  %>                  
                                    <%= text_field_tag :starts_with, params[:starts_with], onkeyup: "$(this).parent('form').submit();", placeholder: "Anything you want?" %>
                                <% end %>
                        </div>
                   </div>
                   <div class="view-product">
                      <%= render 'products' %>
                    </div>   	<!--view-product-->
                </div>
            </div>

       </div>
        <div id="number">

            <div class="pages empty" >
      <div class="empty">
      </div>
      <span style="text-align: right;">
    
          <%= will_paginate @products %>
      <div class="empty">
      </div>
            </div>

    <div class="ship">
        <div class="check">
         <%= image_tag("shipfree.png", :style => "width:180px;padding:2px 0 1px;")%><p>Everywhere</p>
        </div>
        <div class="check">
          <%= image_tag('fresh2.png', style: "height:100px;width:80px;") %><p>Everything</p>

        </div>


    </div>
        </div>

</div>

app/views/products/index.js.erb
<% if @products.count == 0 %>
$('.view-product').html("<div class='notify long_notify'><strong>NOTIFY</strong><span>Dont have product in this catalog</span></div>");
<% else %>
$('.view-product').html("<%= j render 'products' %>");
<% end %>

app/views/products/new.html.erb
<%= form_for @product do |f| %>

<% if @product.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@product.errors.count, "error") %>.
        </div>
        <ul>
            <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :price %>
    <%= f.number_field :price %>

    <%= f.label :discount %>
    <%= f.number_field :discount %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, cols: 50 %>

    <%= f.label :total %>
    <%= f.number_field :total %>

    <%= f.label :image %>
    <%= f.file_field :image %>

    <%= f.label :catalog %>
    <%= f.select :catalog, Product.catalogs.keys, prompt: "Select catalog for product" %>
    
    <%= f.label :source %>
    <%= f.country_select :source, include_blank: false, only: ["VN", "US", "GB", "FR", "TH", "JP"] %>

    <%= f.submit "Create Product" %>
<% end %>

app/views/products/show.html.erb
 <div class="content6">
        <div id="header_detail_pro">
             <p><%= @product.catalog %></p>
             <p id="hover_p"><i class="fa fa-heart" aria-hidden="true"></i> I Love It!</p>
        </div>
        <div id="detail_pro">
            <div style="padding:10px;">
      
                <%= image_tag(@product.image.url(:medium), :style => "border-radius:50% 50%;") %>
            </div>
            <div style="padding:10px;">
                <p><strong><%= @product.name %></strong></p>
                <p style="color:tomato;"><%= number_to_currency(@product.price) %></p>
                <% if @product.total > 0 %>
                <p style="font-style:italic;color:green;">Stock: <%= @product.total %></p>
                <% else %>
                <p style="font-style:italic;color:green;">Out of Stock</p>
                <% end %>
            </div>
            <div>
                <% if @product.total != 0 %>
                <%= link_to "Buy now", line_items_path(product_id: @product.id), :style => "background:tomato;color:white;border:none;padding:20px 50px;margin:20px 0 0 40px;position: absolute;", method: :post %>
                <% else %>
                <%= link_to "Out of Stock", :style => "background:tomato;color:white;border:none;padding:20px 50px;margin:20px 0 0 40px;position: absolute;" %>
                <% end %>
            </div>
        </div>
        <div id="description">  
            <%= truncate(strip_tags(@product.description), length: 250) %>
        </div>
        
    </div>