config/routes.rb
Rails.application.routes.draw do



  ActiveAdmin.routes(self)
  root 'layouts#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  
  get '/blog' => "layouts#show"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  get '/shop', to: 'products#index'
  resources :orders
  resources :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController

  skip_authorization_check
  def index
    @products = Product.where('total > 0').order("view desc").limit(5)
  end

  def show
    
  end
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Rails -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Oswald" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Russo+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Exo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster|Lobster+Two" rel="stylesheet">
    <title>VEGETABLEs</title>
  </head>

  <body>
    
    <div class="mid">
      <div class="container">
          <div class="header">
              <div class="logo">
                <%= link_to "CHANRAU.NET", root_path %>
              </div>
              <div class="menu">
                  <ul>
                      <li><%= link_to "Home", root_path %></li>
                      <li><%= link_to "Blog", blog_path %></li>
                      <li  id="li_hover"><%= link_to "shop", shop_path, method: :get %></li>
                      <% if !logged_in? %>
                      <li><%= link_to "sign in", login_path %></li>
                      <li><%= link_to "sign up", signup_path %></li>
                      <% else %>
                      <li><%= link_to current_user.name, current_user %></li>
                      <li><%= link_to "logout", logout_path, method: :delete %></li>
                      <% end %>
                      <li><%= link_to "<i class='fa fa-shopping-cart' style='font-size: 150%'></i>".html_safe, @current_cart %></li>
                  </ul>
              </div>
          </div>

          <% flash.each do |message_type, message| %>
                <div class="<%=message_type %>" id="flash"><strong><%= message_type %></strong><span><%= message %></span></div>
            <% end %>
    <%= yield %>
    <footer>
      <div class="footer-sumary">
          <div class="about">
              <div class="name-about">
                  <p>OUR TEAM</p>

              </div>
              <div class="name-about">
                  <p>ADDRESS</p>

              </div>
              <div class="name-about">
              
              </div>
              <div class="name-about">
                  

              </div>
              <div class="detail-about" id="our_team">
                <iframe width="300px" height="100%" src="https://www.youtube.com/embed/DOT15xaX7-E?start=12" frameborder="0" allowfullscreen></iframe>
              </div>
              <div class="detail-about" id="detail_about_span">
                <ul>
                   <li><i class="fa fa-check" aria-hidden="true"></i><a href="#"> Trụ sở 1:H8 Mậu Thân , Cần Thơ. Việt Nam</a></li>
                   <li><i class="fa fa-check" aria-hidden="true"></i><a href="#"> Trụ sở 2:Vik 2 , Trần Văn Hoài , Cần Thơ , Việt Nam</a></li>
                   <li><i class="fa fa-check" aria-hidden="true"></i><a href="#"> Mail: americanTeam@gmail.com</a></li>
                   <li><i class="fa fa-check" aria-hidden="true"></i><a href="#"> Liên Hệ: 122429121996</a></li>

                </ul>
              </div>
            
            <div class="detail-about" id="map">
               <div>
                  <script src='https://maps.googleapis.com/maps/api/js?key=AIzaSyDBsOFaxrzhBjLNw20cvOEMj63_Bgrwdt4&callback=initMap'></script><div style='overflow:hidden;height:250px;width:250px;'><div id='gmap_canvas' style='height:250px;width:250px;'></div><div><small><a href="https://embedgooglemaps.com/en/how-to-embed-google-maps-into-your-website/">embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 									embedgooglemaps.com 																		embedgooglemaps.com</a></small></div><div><small><a href="http://buyinstagramfollowersreviews.net/">Visit BIFR.COM/</a></small></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style></div><script type='text/javascript'>function init_map(){var myOptions = {zoom:16,center:new google.maps.LatLng(10.034499800000406,105.7733476407532),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(10.034499800000406,105.7733476407532)});infowindow = new google.maps.InfoWindow({content:'<strong>ChanRau</strong><br>h8 cao thắng, Mậu Thân Xuân Khánh Ninh Kiều<br>'});google.maps.event.addListener(marker, 'click', function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>
               </div>
              </div>
        </div>
        </div>
      </div> 
      
      <div class="footer">
        <div class="copyright">
          <p>copyright	&#169; by americanTEAM</p>
        </div>
        <div class="icon-contact">
                <a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>

        </div>
        </div>
    </div>
</div> <!-- container -->

</div>
    </footer>
    <script type="text/javascript">
      $(document).ready(function(){
        setTimeout(function(){
          $('#flash').hide('blind');
        }, 3000);
       })
      </script>
  </body>
</html>

app/views/layouts/index.html.erb
<div class="content">
    <div class="slider">
        <div class="box">
            <p style="font-size:300%;">ORGANIC</p>
            <p style="font-size:300%;color:rgb(215, 214, 40);" >VEGBOXES</p>
            <p style="font-family: 'Bree Serif', serif;font-size:150%;">FROM $9.99</p>

        </div>
    </div>
    <div class="instead">
        <%= link_to products_path(:catalog => 'Leafy and salad vegetables') do %>
        <div id="item1" class="item">
            <p>Leafy and</p>
            <p>Salad</p>
        </div>
        <% end %>
        <%= link_to products_path(:catalog => 'Fruits') do %>
        <div id="item2"  class="item">
                <p>Fruit</p>
                <p>More Fruit</p>
              </div>
          <% end %>
        <%= link_to products_path(:catalog => 'Flowers and flower buds') do %>
        <div id="item3"  class="item">
          <p>Flowers and </p>
          <p>Flower Buds</p>
        </div>
        <% end %>
        <%= link_to products_path(:catalog => 'Podded vegetables') do %>
        <div id="item4"  class="item">
          <p>Podded</p>
          <p>Vegetables</p>
        </div>
        <% end %>
    </div>
    <div class="organic">
        <p style="font-size:150%;font-family: 'Merriweather', serif;">Best Seller</p>
        <p style="font-weight:600;font-size:85%;">WHEN QUALITY MATTERS TO YOU AND YOUR CUSTOMERS</p>
    </div>
    <div class="product">
     <% @products.each do |product| %>
        <div class="detail-product">
           <div class="dit_me_2"><p style="color:white;"><i class="fa fa-plus" aria-hidden="true"></i></p></div>
           <% if product.discount !=0 %>
           <div class="discout"><p style="color:white;background:tomato;margin-left:120px;margin-top:-7px; border-radius:50% 50%;">-<%= product.discount %>%</p></div>
           <% end %>
           <div class="dit_me">
              <%= link_to "<p style='color:white;'>ADD <i class='fa fa-plus' aria-hidden='true'></i></p>".html_safe, line_items_path(product_id: product.id), method: :post %>
            </div>
            <div class="img_pro_detail">
              <%= image_tag(product.image.url(:medium)) %>
            </div>
            <div class="p_pro_detail1"><p><%= product.name %></p></div>
            <div class="cost"><p class="<%= 'line' if product.discount != 0 %>",style="color:grey;font-weight:500;" ><%= number_to_currency(product.price) %></p></div>
            <% if product.discount != 0 %>
            <div class="discout_2"><p style="color:tomato;padding-top:0;padding-bottom:0;"><%= number_to_currency(product.price_discout) %></p></div>
            <% end %>
        </div>
    <% end %>
    </div>
    <div class="news">
         <div class="like_news">
            <p style="font-size:150%;font-family: 'Merriweather', serif;">Do You Know?</p>
            <p style="font-weight:600;font-size:85%;">WHEN QUALITY MATTERS TO YOU AND YOUR CUSTOMERS</p>
        </div>
        <div class="choose">
          <div class="img-choose1">
              <a style="color:white;" href="blog.php"><p>ITALIAN SAUSAGE SOUP WITH</p>
              <p>WHITE BEANS AND SPINACH</p>
              <p style="font-weight:200;font-size:80%;">Well hello there from an 80-degree October day in New Jersey...</p></a>
          </div>
          <div class="img-choose2">
            <a style="color:white;" href="blog"><p>VISIT OUR ORGANIC RESTAURANT</p>
            <p style="font-weight:200;font-size:80%;">Well hello there from an 80-degree October day in New Jersey...</p></a>
          </div>
          
        </div>
        <div class="choose">
          <div class="img-choose1">
             <a style="color:white;" href="blog.php"><p>ITALIAN SAUSAGE SOUP WITH</p>
              <p>WHITE BEANS AND SPINACH</p>
              <p style="font-weight:200;font-size:80%;">Well hello there from an 80-degree October day in New Jersey...</p></a>
          </div>
          <div class="img-choose2">
            <a style="color:white;" href="blog"><p>VISIT OUR ORGANIC RESTAURANT</p>
            <p style="font-weight:200;font-size:80%;">Well hello there from an 80-degree October day in New Jersey...</p></a>
          </div>
            
          
        </div>

    </div>


</div> <!-- content -->

app/views/layouts/show.html.erb
<div id="blog_bonus">
        <div class="header_blog">
            <p>BLOG <i class="fa fa-sticky-note" aria-hidden="true"></i></p>
        </div>
        <div class="info_blog">
            <p style="padding:10px;border-bottom:1px solid rgba(0,0,0,.1);"><strong>ITALIAN SAUSAGE SOUP WITH WHITE BEANS AND SPINACH</strong></p>
            <p style="text-indent:40px;font-style:italic;font-size:90%;padding:20px;">Well hello there from an 80-degree October day in New Jersey. I’m not complaining, but I’m also not about to be demure with the soup. It’s decorative gourd season, mofos. (Never gets old, am I right?) And that means it’s soup season too. Second time in a week (oh hi, Monday soup), and I’m not sorry. Today we’re all about Italian sausage soup with white beans, spinach and pasta shells.</p>
            <p style="text-indent:40px;font-style:italic;font-size:90%;padding:20px;">This easy soup sports a tomato-ish broth situation. It’s hearty and veggie-packed. It feeds a small crowd or a family for a couple of weeknight dinners. It’s quick to make. And we’re eating it for dinner this very evening, in a house that’s getting stuffy because I’m too lazy to open the windows. I mean, I’d open them, but then I might have to close them in the morning if it’s freezing, and that’s just hard.</p>
            <p style="text-indent:40px;font-style:italic;font-size:90%;padding:20px;">I blame decorative gourds.</p>
            <%= image_tag("soupblog.jpg", :style => "width: 100%") %>
            <p style="text-indent:40px;font-style:italic;font-size:90%;padding:20px;">Here’s a protip for anytime you make soup with pasta in it. Consider cooking the pasta separately and tossing it with a little olive oil. Then, when you’re ready to serve, stir some pasta into the soup in each individual serving bowl. That way the pasta won’t slurp up all the broth before you have a chance to. This is an especially good idea when you might have leftovers. You know I’m not into shoulds. But this is a good call, just sayin.</p>
            <p style="text-indent:40px;font-style:italic;font-size:90%;padding:20px;">That’s all for today. Talk to you soon.</p>
        </div>
    </div>